 export const EmployeeData=[
    {
        id:1,
        firstName:"chin",
        lastName:"praja",
        Age:21,
    },
    {
        id:2,
        firstName:"cgu",
        lastName:"patel",
        Age:22,
    },
    {
        id:3,
        firstName:"fn",
        lastName:"patel",
        Age:52,
    }
]